### ISSUE TITLE
How to process unsual flowering times

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits.build#110]
E.g. in Hughes_1992, we have values like

```
Mar - May; Oct - Dec
Feb - Apr;Jul - Aug
```
which currently come back as NA

**Comment by ehwenk** [comment]
In RBGSYD_2014_2, "all year" is being converted to `NA`. Run the following to see a list of values that are in the `data.csv` file that aren't being converted to data in austraits:
```
read_csv("data/RBGSYD_2014_2/data.csv") %>%
  filter(trait == "flowering month") %>%
  distinct(species) %>% rename(original_name = species) %>%
  mutate(available = "data_available") -> species_with_RBG_data

austraits$traits %>%
  filter(trait_name == "flowering_time") %>%
  filter(dataset_id == "RBGSYD_2014_2") %>% 
  select(taxon_name, original_name, value) %>%
  full_join(species_with_RBG_data) %>% 
  filter(is.na(taxon_name)) -> missing_data

read_csv("data/RBGSYD_2014_2/data.csv") %>%
  filter(trait == "flowering month") %>%
  filter(species %in% missing_data$original_name) %>% View()
```

**Comment by ehwenk** [comment]
In Craven_1987, 5 instances of "all year" were being missed, because it says "all year" in both the "beginning month" and "end month" columns, so will appear as "all year-all year" after the two columns are combined by custom R code. A long-term option is in the function `format_flowering_months` replace "all year-all year" with "all year". For now I used custom R code to replace the beginning "all year" with "1" and the ending "all year" with "12"

**Comment by GaryTruong** [comment]
> In Craven_1987, 5 instances of "all year" were being missed, because it says "all year" in both the "beginning month" and "end month" columns, so will appear as "all year-all year" after the two columns are combined by custom R code. A long-term option is in the function `format_flowering_months` replace "all year-all year" with "all year". For now I used custom R code to replace the beginning "all year" with "1" and the ending "all year" with "12"

The functions actually have no issue with "all year-all year" 
```
> convert_month_range_vec_to_binary("all year-all year")
[1] "yyyyyyyyyyyy"
```
 The issue here is that `format_flowering_months()` calls `get_month()`. When the beginning and end months are numbers they return an abbreviated month. But with 'all year' it returns an NA so it doesnt make it past that step. The only solution here is to do what you have done and use custom R code to convert the "all year" to 1 and 12
