### ISSUE TITLE
Taxonomic names: updates to algorithm for name matching

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#553]
A series of small changes to be made to the taxonomic names matching protocol:

- [ ] Use string search-and-replace to update wording:

1. For hybrids, if pattern ` x  ` exists within the taxon name, then "genus species x genus species" is automatically reformatted to "genus sp. (species species x genus species)" - this has to happen after the first round of alignments, since there are some "accepted" hybrids that need to be recognised before the reformatting occurs.  (Lizzy already drafted these on a branch)

2. Similar for instances of "genus species/species" and "genus species aff." become " genus sp. [original name] (Lizzy already drafted these on the branch https://github.com/traitecoevo/austraits.build/tree/taxonomic_names_updates

- [ ] Each taxon name would be aligned at the highest rank possible; For two-word taxon names the matching search would begin at the species level and for three+-word taxon names the matching would begin at the infraspecific level. If an exact or fuzzy match isn't possible for all words, matching would then be attempted with "n-1" words, working backwards from infraspecific, (3 words) to species (2 words), to genus (1 word) to family (1 word). 

- [ ] The actual taxon name, whether it is recognised or not, would be maintained as the `taxon_name`. In addition, in the table `austraits$taxa` there would be columns for `family`, `genus`, `species` (2 word species name, not just species epitet) and `infraspecific` (3 word species name). The highest rank at which a match could be made would be documented in a column `rank`.  As many columns as possible would be filled in, with those that aren't applicable left blank. For instance `Eucalyptus sp. scaly bark` would be kept as the taxon_name, with `family` and `genus` filled in, `rank` listed as `genus` and `species` and `infraspecific` left blank.
- [ ] Related, allow matches to be made with scientific authority; probably an extra argument in the function `metadata_check_taxa` which switches to using a column in the APC/APNI files that includes authority
- [ ] Related, Require user approval before allowing matches that change to a different family (or genus, but I think family is good enough) (Issue #451)

This issue closes #527 and closes #498

**Comment by ehwenk** [comment]
There should be two taxon_rank columns:

`taxon_rank_resolution`: what is the most specific resolution match possible for a given name)
`taxon_rank_applicability`: what is the taxon rank that the name refers to – to make absolutely clear that names that can only be resolved to the genus, actually only are referring to a species

**Comment by ehwenk** [comment]
Previous thoughts, in greater detail, with exact sequence for how algorithm can best match names: 

@dfalster @eflowerproject can you provide feedback?

1. Reform at any name with ` aff. ` (note “spaces”) to read “genus sp. [genus aff. species]
2. Match entire name, including using fuzzy matching
      a.	Genus name changes cannot change first 3 letters (throughout… but only mentioned here)
      b.	As previously, ignore `genus sp.` (& variants)
      c.	Add an argument that allows previously made changes to be part of this fuzzy matching (has become an issue if subsequent APC/APNI files have slightly different phrase name syntax or spelling)
      d.	Add an argument that allows matches to be made to the scientific name, instead of the canonical name
3.	Reformat any unmatched hybrid species to read “genus sp. [genus species x genus species 2] (hybrids are identified by an instance of ` x ` in their names (note “spaces”)
4.	For remaining taxa, run fuzzy matching function just on first 3 words; ignore `genus sp.` (& variants)
      a.	In this step, should only be picking up taxon names at the subspecies or variety rank
      b.	If a name matches to `3 words` but not to the entire string, it will be automatically reformatted as `genus species infraspecific_epithet [rest of words]`
      c.	`resolution_rank` and `applicability_rank` will be assigned as variety or subspecies
5.	For remaining taxa, run fuzzy matching function just on first 2 words; ignore `genus sp.` (& variants)
        a.	In this step, should only be picking up taxon names at the species rank.
        b.	If a name matches to `2 words` but not to the entire string, it will be automatically reformatted as `genus species [rest of words]`
      c.	`resolution_rank` and `applicability_rank` will be assigned as species
6.	Reformat any unmatched names to read ` genus sp. [notes]` (notes include anything that isn’t the first word or sp.)
7.	For remaining taxa, run fuzzy matching function just on first word
      a.	Now, for the first time, include names that had `sp.` (& ssp, sp, etc) as the second “word”
      b.	Names should only be matched to `genus` or `family` level taxa from APC/APNI. 
      c.	This allows `genus sp.` to have typos corrected, including typos for outdated names
      d.	Assign `resolution rank` to either genus or family, as appropriate
      e.	For any name where the second “word” is “sp.” the `applicability rank` is species; 
                 **I feel like there is a manual step here, to distinguish between entries that represent a genus-level outcome (i.e. from floras) versus plants identified only to genus. The first should be only a single word (genus; or family) while the later should be `genus sp.`
8.	Fill in columns for family, genus, species, infraspecific
      a.	Fill in as many columns as applicable, given the value in `taxon_resolution`; data are matched from APC, APNI
      b.	These columns are separate from `taxon_name` which is the typo-corrected, best-match name, that still includes notes. This is an easy way people can join in the taxon table and then filter for a certain group.
9.	In cases where a name is simply `genus sp.`, it should be reformatted as `genus sp. [dataset_id]`. This is to ensure that for those genera where there are a lot of `genus sp.` identifications, there isn’t any confusion that these all refer to the same species, across studies.

**Comment by eflowerproject** [comment]
Hi @ehwenk @dfalster apologies about delay, please see my replies below:

1. Sounds OK, though the alternative would be to treat aff. as indet. (i.e., genus only)
2a. Makes sense
2b. Makes sense
2c. Don't fully understand
2d. Don't fully understand, if the difference is inclusion of author then yes, this makes full sense
3. Yes and no; I can't see good reasons to keep hybrids in AusTraits and it seems even worse to want to pool their trait data at the genus level; also hybrid nomenclature practices vary; I would exclude all cases of A b x A c, but we could discuss what to do in cases of A x d, which tend to be long-standing species names that were later recognised as hybrids, but are so distinct that botanists have chosen to retain their name instead of referring to them by the two parents (or because said parents remain uncertain or are more than two); many of these A x d situations are also often spelled A d (which would require a unique type of matching: remove x prior to matching)
4. Note your use of genus sp. in describing the algorithm is confusing to a botanist: I read unidentified species in a genus (e.g., Solanum sp.) instead of generic full species name (e.g., Solanum lycopersicon); if you refer to the latter I would write "genus epiteth"; [2 min later] now I realise you probably referred to the former, but now I am super confused by "(& variants)": I initially thought by variants you meant infraspecific taxa (varieties and subspecies)
4a. Makes sense, though it means in some cases you will be considering varieties (directly under species level) and in others not (varieties of subspecies); none of these ranks have much biological meaning but I would intuitively tend to ignore all varieties; I definitely see the value of the proposed approach for name matching though, but in this case I do wonder why not match the full 4 words when they occur
4b. OK
4c. OK
5. OK
6. I would not reformat those things: I would exclude from AusTraits, or check and resolve manually those unmatched names
7. I see limited value to this, for reasons discussed previously; there are too many cases in botany where synonymiies are more complicated than A = B (where A and B are genera) and synonymies between genera can only be done at the subspecies level (e.g., A x = B y, but A z = C w); if you include such data in AusTraits, I would suggest to issue a strong warning
8. Not sure I follow through, but in my opinion there is a strong risk in using species as a column with just the epiteth if that is what you mean
9. Good point, although it would be cleaner and more straightforward to simply exclude all those names and their data; also note that even within the same dataset you have absolutely no guarantee that two data points recorded under a given genus sp. actually refer to the same species :-(

**Comment by ehwenk** [comment]
@eflowerproject 

Hervé, I was thinking more about the hybrids (at least those hybrids that aren't `accepted names` per APC. You're right that using `genus sp.` implies that the plant is a "species", which it isn't. What if those were coded as `genus x [genus species1 x genus species2]`?

And talking to Daniel and David, we will have two easy filters (in the API, and future AusTraits releases). First to filter for `APC accepted` vs `APNI` vs `unknown`. Second, to filter out phrase names and hybrids (within the `APC accepted` names) to subset AusTraits quickly to only include data on plants identified to a known, accepted binomial/infraspecific.

Also, for APC species, there will now be an explicit column in the taxon table identifying each taxon as `native`, `naturalised` or `native + naturalised`.
