### ISSUE TITLE
Traits with a range of values, where the "ranges" aren't min-max ranges, but approximations/buckets

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#568]
For a number of the fire response-related traits, including seed longevity and time to maturity, trait values are often given as ranges, that represent categorical "buckets". E.g. <1 year, 1-5 years, 5-20 years, >20 years. Since different authors have different break points for the same trait, it would be nice to convert these into numeric values. Otherwise the number of "categorical values" proliferates, with endless ranges as categories. However, it isn't obvious what the best approach is, since these ranges aren't min-max ranges for a given species, but rather that a species' value fits into one of the range-buckets.

Suggestions?

**Comment by T-LeB** [comment]
Let me know if im doing this wrong but rather than starting a separate issue i thought i'd add this here as it is related to this one. where these values have been entered as a range e.g. 3-5 excel automatically converts them to a date or date number e.g. 3 May 2022 and theres no way I've found to undo it. Not sure if the same problem occurs when read into R. But it makes skimming the data in excel a bit tricky. 

And not sure if its my place to make a suggestion on this issue but having used this kind of trait data to inform threatened species risk assessments before having seperate upper, lower and best/mean estimates can be a useful way to make sense of a these buckets in the absence of more accurate estimates. Not sure if seperating a trait into subsets like that works with the structure of AusTraits though.

**Comment by dfalster** [comment]
Hi Tom, Thanks very much. I'll let @ehwenk followup on the specifics. I just wanted to let you know that Your feedback is very welcome and to encourage you to post issues/feature requests. 

yes, the excel date conversion is very annoying and we definitely want to avoid the automatic conversion to dates.

> having used this kind of trait data to inform threatened species risk assessments before having seperate upper, lower and best/mean estimates can be a useful way to make sense of a these buckets in the absence of more accurate estimates.

Can you provide an example?

**Comment by T-LeB** [comment]
Hi Dan,

Thanks for the response.

I’m not talking about anything complex in implementation or usage. Just potentially having separate trait categories for the upper estimate, lower estimate and potentially a mean or middle estimate.e.g.

  *   reproductive maturity upper = 5 yrs
  *   reproductive maturity lower = 3 years
  *   reproductive maturity mean = 4 years

Then in terms of the usage of this kind of data, the way I’ve used it is less trait oriented but you can explore how the different estimates relate to the fire frequencies species are experiencing. Without a more definitive measurement of age of reproductive maturity I think generally incorporating the uncertainty is the best way to go rather than choosing a single value such as the mean.

As I said though, if you were to implement it this way I cant see any reason why it wouldn’t be implemented for any other trait which could be presented as a range which might not be desirable.

Cheers

Tom

**Comment by ehwenk** [comment]
Hi Tom, @T-LeB 

Thanks for posting. Your concern that reverting from separate min/max values to a single range will indeed cause problems in Excel, which we hadn't considered and we will contemplate other solutions before proceeding with this. I know this problem well and have been frustrated by it repeatedly.

And we are developing a summary of AusTraits dataset values that will report species-level mean, min, and max values for numeric traits. This should be included in our next Zenodo release, due in the coming months. Right now we are working toward having overall AusTraits values, but we will think about adding functionality to the code that lets the data be summarised by site as well.

Lizzy

**Comment by ehwenk** [comment]
To follow up, we will include `bin` and `range` as additional value_types. To avoid the problem of Excel interpreting `dashes` as dates, we'll use the format 3--5 (for both bins and ranges)

**Comment by ehwenk** [comment]
closed with [4dab6ab](https://github.com/traitecoevo/austraits.build/commit/4dab6abb49ba58ff28dfdfffde20d98064e838dd)
