### ISSUE TITLE
Optimise metadata_create_template

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits.build#589]
Some ideas for further optimising `metadata_create_template` function. 

Better defaults in manual sections
1. In the manual section, where we enter columns, can we update so that the option for NA is the first option and has number 0? That way it always displays first and is easy to type. Currently it appears last and will have a different number every time, depending on the number of columns.

2. After running the basic `metadata_create_template` and without entering trait info, if your run remake it fails, and with a cryptic error message. Perhaps we should have it either 
- fail and say no traits specified
- proceed and just not include any data.

**Comment by ehwenk** [comment]
1. I like the idea of having the NA option always assigned the number 0. It is time consuming to always have to search through the list for the number accompanying `NA` - since this is the most commonly used option.

2. I would recommend that in this case remake proceeds, but just does not include any data. There could also be a message that specifies study/studies for which there is no data.

**Comment by ehwenk** [comment]
Yes and no - still relevant, but low priority, given none of us have been frustrated by these errors during the recent data input campaign
