### ISSUE TITLE
Leaf Mass per Area

### ISSUE THREAD

**Issue by klapierre** [traitecoevo/austraits.build#663]
---

In the most recent version (4.1.0), SLA is no longer included but leaf mass per area is. These should be inverses, but when I inverse the leaf mass per area values they are all really small numbers (mean: .0105386, max: 0.3763720).  Other trait databases (TRY and BIEN) have values for the same subset of species that are much larger (e.g., BIEN mean: 26.77, max: 349.74).  Is there an issue with the leaf mass per area data?

What a great database you've assembled, thanks!

```r
library(austraits)
library(tidyverse)

austraits <- load_austraits(version = "4.1.0", path = "data/austraits")

traits <- summarise_austraits(austraits, "trait_name")

data <- extract_trait(austraits, c('leaf_mass_per_area'))

traitData <- data$traits%>%
  mutate(value=1/value,
         trait_name='leaf_mass_per_area')

summary(traitData$value)
```

**Comment by ehwenk** [comment]
Thanks for the message. You're right that we've decided to invert from SLA to LMA, since this matches our other "mass per area" traits. I think what you're noticing is that the units aren't simply inverted. The standard units for LMA are `g/m2` while the units for SLA are most commonly `mm2/mg` (at least that is what we used). This means when you invert from SLA in mm2/mg to LMA in g/m2 you also have to multiply the values by 1000. - Lizzy
