### ISSUE TITLE
Move to traits.build

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits.build#754]
I have started moving code from `austraits.build` over to `traits.build` -- see https://github.com/traitecoevo/traits.build

**Comment by roblanf** [comment]
Will this repo remain? Since it's referenced in the AusTraits paper as the place to come and report any issues, it seems like it should stick around.

**Comment by ehwenk** [comment]
@roblanf Yes, austraits.build will continue to be the repo for the AusTraits database with all data files, metadata files stored here. But instead of the R workflow also being part of this repo, the AusTraits plant trait database will be compiled using the traits.build package. The R files that build AusTraits were initially identical between the two repos, but began diverging in late June. We're continuing to develop the workflow only at traits.build and will shortly be swapping AusTraits to be built by traits.build.
